version: 2

project_name: gctx

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gctx
    main: .
    binary: gctx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/Poimidorka/gctx/cmd.version={{ .Version }}

archives:
  - id: default
    ids:
      - gctx
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: gctx
    ids:
      - default
    binaries:
      - gctx
    repository:
      owner: Poimidorka
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://github.com/Poimidorka/gctx
    description: Small Git context switcher
    dependencies:
      - formula: git
